# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RolodexApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RolodexApp
  pod 'Alamofire', '~> 4.6'
  pod 'SwiftyJSON', '~> 4.0'
  target 'RolodexAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RolodexAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
